project_name: cx-keycloak-utils
env:
  - GO111MODULE=on
  - GOPRIVATE="github.com/sonatype"
  - CGO_ENABLED=0
builds:
  - id: add-to-innovators-group
    binary: cx-add-to-innovators-group
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    main: ./cmd/cx-add-to-innovators-group
archives:
  - id: default
    builds:
      - add-to-innovators-group
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: mac
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
